---
# ConfigMap dla konfiguracji Nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-honeypot-config
  namespace: honeypot
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Format logowania dla honeypota
        log_format honeypot '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" "$request_body"';
        
        access_log /var/log/nginx/access.log honeypot;
        error_log /var/log/nginx/error.log;
        
        sendfile on;
        keepalive_timeout 65;
        
        # Celowo włączone pokazywanie wersji serwera (podatność)
        server_tokens on;
        
        server {
            listen 80 default_server;
            server_name _;
            
            # Główny katalog
            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
                # Celowo włączone listowanie katalogów (podatność)
                autoindex on;
            }
            
            # Fałszywy panel administracyjny
            location /admin {
                alias /usr/share/nginx/html/admin;
                index login.html;
            }
            
            # Fałszywy phpinfo
            location ~ \.php$ {
                root /usr/share/nginx/html;
                # Celowo błędna konfiguracja
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
            }
            
            # Podatna ścieżka upload
            location /uploads {
                root /usr/share/nginx/html;
                autoindex on;
                # Celowo włączone metody HTTP (podatność)
                dav_methods PUT DELETE;
            }
        }
    }
  admin-login.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Admin Panel</title>
        <style>
            body { font-family: Arial; margin: 40px; }
            .login-form { width: 300px; margin: 0 auto; }
            input { width: 100%; padding: 8px; margin: 5px 0; }
            button { padding: 10px; background: #4CAF50; color: white; border: none; }
        </style>
    </head>
    <body>
        <div class="login-form">
            <h2>Admin Login</h2>
            <form method="post" action="/admin/login">
                <input type="text" name="username" placeholder="Username">
                <input type="password" name="password" placeholder="Password">
                <button type="submit">Login</button>
            </form>
        </div>
    </body>
    </html>
  info.php: |
    <?php
    // Celowo podatny plik PHP
    phpinfo();
    ?>

---
# Deployment dla Nginx Honeypot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-honeypot
  namespace: honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-honeypot
  template:
    metadata:
      labels:
        app: nginx-honeypot
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: admin-page
          mountPath: /usr/share/nginx/html/admin/login.html
          subPath: admin-login.html
        - name: php-info
          mountPath: /usr/share/nginx/html/info.php
          subPath: info.php
        - name: uploads-dir
          mountPath: /usr/share/nginx/html/uploads
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-honeypot-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: admin-page
        configMap:
          name: nginx-honeypot-config
          items:
          - key: admin-login.html
            path: login.html
      - name: php-info
        configMap:
          name: nginx-honeypot-config
          items:
          - key: info.php
            path: info.php
      - name: uploads-dir
        emptyDir: {}

---
# Service dla Nginx Honeypot
apiVersion: v1
kind: Service
metadata:
  name: nginx-honeypot
  namespace: honeypot
spec:
  selector:
    app: nginx-honeypot
  ports:
  - port: 80
    targetPort: 80
  type: NodePort